# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        chain_provider:
            chain:
                providers: [in_memory, database]
        
        in_memory:
            memory:
                users:
                    david:
                        password: $2y$12$JHEAW5PMU3M391nmNoR9seyvpG2hIMu0BRTVc1SIKhBoFUZTJ0ukO
                        roles: 'ROLE_USER'
                    admin:
                        password: $2y$12$ULd/k8UJy2FCSw5lMvrVx..RO12/tltE0zfFxqslcStCIWuPsbg06 
                        roles: 'ROLE_ADMIN'
        database:
            entity:
                class: AppBundle\Entity\User
                property: username 
    encoders:
        Symfony\Component\Security\Core\User\User: 
            algorithm: bcrypt
            cost: 12
            
        AppBundle\Entity\User:
            algorithm: bcrypt
            cost: 12
    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            # activate different ways to authenticate

            #http_basic: ~
            provider: database
            
            form_login:
                login_path: login
                check_path: login
            logout:
                path: /logout
                target: /
    access_control:
        - { path: ^/[a-zA-Z]+/\d+/(?:edit|delete), roles: ROLE_ADMIN }
        - { path: ^/[a-zA-Z]+/new, roles: ROLE_USER }
    role_hierarchy:
        ROLE_ADMIN: ROLE_USER

